#ifndef HELPLMP3_H
#define HELPLMP3_H

#include <iostream>
#include "Programheader.h"

inline void ShowHelp() {
   ShowProgramHeader("CmdLMP3 -- P3 Lattice Matching");
   std::cout <<
      "; CmdLMP3 -- P3 Lattice Matching\n"
      ";\n"
      "; Finds transformation matrices relating two or more crystal lattices,\n"
      "; including supercell/subcell relationships.\n"
      "; an extension of Andrews&Bernstein, 2026\n"
      ";\n"
      "; INPUT FORMAT\n"
      ";   One lattice per line: <centering> a b c alpha beta gamma\n"
      ";   The centering symbol may also be given AFTER the six cell\n"
      ";   parameters instead of before: a b c alpha beta gamma <centering>\n"
      ";   Centerings: P I F A B C R H\n"
      ";   Example:  P 5.0 5.0 7.0 90 90 120\n"
      ";   Finish input with:  end\n"
      ";\n"
      "; CONTROL KEYWORDS (enter before 'end')\n"
      ";\n"
      ";   HELP  or  ?\n"
      ";      Show this message.\n"
      ";\n"
      ";   DETAILS\n"
      ";      Show extended diagnostic output during matching, including\n"
      ";      separate primitive-frame and reference-frame P3/S6 numbers\n"
      ";      for each match -- the most useful tool for checking WHY a\n"
      ";      particular cell pair is or is not shown as CONVENTIONAL.\n"
      ";\n"
      ";   MODE <ALL | SUPER | EQUIVALENT>\n"
      ";      ALL        Search det=1 and det=2,3,4,5,6 matrices (default)\n"
      ";      SUPER      Search only supercell matrices (det=2,3,4,5,6)\n"
      ";      EQUIVALENT Search only equivalent-lattice matrices (det=1)\n"
      ";\n"
      ";   USEHNF\n"
      ";      HNF (Hermite Normal Form) is a standardized upper-triangular\n"
      ";      representation of supercell transformation matrices. For a given\n"
      ";      supercell order n, HNF provides the minimal complete set of\n"
      ";      distinct supercell relationships for primitive cells\n"
      ";      (Santoro & Mighell, Acta Cryst. A28, 284-287, 1972).\n"
      ";      Counts: det=2: 7, det=3: 13, det=4: 35, det=5: 31, det=6: 91.\n"
      ";      Hermite Normal Form (HNF): a transformation matrix of the form\n"
      ";         [ a  b  c ]        a, d, f > 0\n"
      ";         [ 0  d  e ]        0 <= b < a\n"
      ";         [ 0  0  f ]        0 <= c, e < f\n"
      ";      where the determinant equals a*d*f (the supercell order).\n"
      ";      Every integer supercell matrix is equivalent to exactly one HNF\n"
      ";      matrix under unimodular left-multiplication, making HNF the\n"
      ";      minimal complete set for primitive cells\n"
      ";      (Santoro & Mighell, Acta Cryst. A28, 284-287, 1972).\n"
      ";\n"
      ";      det=5 and det=6 ALWAYS use HNF matrices only, in both modes --\n"
      ";      the brute-force integer search is computationally infeasible\n"
      ";      at those orders, so there is no alternative. USEHNF has no\n"
      ";      effect on det=5,6.\n"
      ";\n"
      ";      By default (USEHNF off), det=2,3,4 are searched using a\n"
      ";      brute-force integer matrix set supplemented by HNF.\n"
      ";\n"
      ";      USEHNF restricts the det=2,3,4 search to HNF matrices only.\n"
      ";      This is faster but is NOT guaranteed complete for a given\n"
      ";      pair of cells: HNF enumerates the minimal complete set of\n"
      ";      supercell relationships only up to relabeling -- every\n"
      ";      relationship has SOME equivalent HNF representation, but only\n"
      ";      if the basis is free to be chosen. Once a primitive cell's\n"
      ";      axes are already fixed (as they are here, coming out of a\n"
      ";      particular Niggli reduction), the transformation matrix\n"
      ";      connecting it to the reference may require a non-upper-\n"
      ";      triangular form, which HNF mode cannot find -- there is no\n"
      ";      fallback. The brute-force (non-HNF) search, working over a\n"
      ";      much larger general matrix space, can still find it. If a\n"
      ";      relationship is suspected but USEHNF does not find it, turn\n"
      ";      USEHNF off, or re-index the cell to a standard setting first.\n"
      ";\n"
      ";   NIGGLIDELTA <value>\n"
      ";      Tolerance for Niggli reduction (default 1e-5).\n"
      ";\n"
      ";   DISPLAYMODE <OLD | NEW | BOTH>\n"
      ";      Controls how each match's REFERENCE / TRANSFORMED MOBILE cell\n"
      ";      pair is shown.\n"
      ";      NEW   (default) Show the reference's own original cell (with\n"
      ";            its actual centering) alongside the mobile transformed\n"
      ";            into that SAME frame, labeled TRANSFORMED MOBILE\n"
      ";            (CONVENTIONAL), when that reference-frame match is good\n"
      ";            enough (see THRESHOLD below). When it is not good\n"
      ";            enough, falls back to the primitive-frame pair instead,\n"
      ";            with a NOTE line explaining why.\n"
      ";      OLD   Always show the primitive-frame pair (primitive\n"
      ";            reference cell vs the matcher's raw transformed mobile,\n"
      ";            both in primitive space). No reference-frame cell is\n"
      ";            attempted or shown.\n"
      ";      BOTH  Internal/debugging use only -- shows both the OLD-style\n"
      ";            primitive block and the NEW-style reference-frame block\n"
      ";            for the same match, so the two can be compared directly.\n"
      ";            Not intended for normal use; combine with DETAILS for\n"
      ";            full diagnostic output of both frames' P3/S6 numbers.\n"
      ";\n"
      ";   THRESHOLD <percent>\n"
      ";      Maximum acceptable reference-frame P3 distance, expressed as a\n"
      ";      PERCENTAGE of the reference cell's own P3 norm (not an\n"
      ";      absolute distance -- a fixed Angstrom cutoff would not be\n"
      ";      scale invariant across cells of very different size). Default\n"
      ";      2.0, matching the GOOD quality tier. Only affects DISPLAYMODE\n"
      ";      NEW/BOTH; raise this value to see reference-frame cells for\n"
      ";      more marginal matches (e.g. a known but distorted\n"
      ";      relationship you still want displayed), lower it to be more\n"
      ";      conservative about what is shown as CONVENTIONAL.\n"
      ";\n"
      ";   CSVOUTPUT\n"
      ";      Reserved; not currently active.\n"
      ";\n"
      ";   TEST [n] [n2] [n3] ...\n"
      ";      Run built-in tests. Omit n (or use 0) to run the full suite;\n"
      ";      supply one or more test numbers to run only those tests, each\n"
      ";      with its own pass/fail summary. TEST can also be repeated on\n"
      ";      separate lines to accumulate the same list, e.g.\n"
      ";         test 6\n"
      ";         test 18\n"
      ";      is equivalent to  test 6 18\n"
      ";      The full suite (no number) also runs a short set of standalone\n"
      ";      match-presentation regression checks at the end.\n"
      ";\n"
      "; SUPERCELL SEARCH NOTES\n"
      ";   det=2,3,4: searched by both brute-force integer matrices and HNF.\n"
      ";   det=5,6:   searched by HNF only (177 matrices total for det=2-6).\n"
      ";\n"
      ";   Hermite Normal Form (HNF) matrices are a standardized upper-\n"
      ";   triangular representation of supercell transformation matrices.\n"
      ";   For a given supercell order n (volume ratio), HNF provides the\n"
      ";   minimal complete set of distinct supercell relationships for\n"
      ";   primitive cells (Santoro & Mighell, Acta Cryst. A28, 1972).\n"
      ";   Counts: det=2: 7, det=3: 13, det=4: 35, det=5: 31, det=6: 91.\n"
      ";\n"
      ";   The brute-force search space for det=5,6 is computationally\n"
      ";   infeasible (~10^10 candidates), so HNF is used exclusively.\n"
      ";   HNF may miss relationships requiring a non-upper-triangular\n"
      ";   transformation matrix. If a det=5 or det=6 relationship is\n"
      ";   suspected but not found, re-index the cell to a standard setting\n"
      ";   before running CmdLMP3.\n"
      ";   det=5 supercells are rare in practice.\n"
      ";\n"
      "; INTERPRETING RESULTS -- WHERE TO LOOK IF SOMETHING LOOKS WRONG\n"
      ";\n"
      ";   P3 distance vs S6 angle measure different things. P3 distance\n"
      ";   reflects the full metric mismatch, including scale/size. S6\n"
      ";   angle reflects only shape (it is computed from normalized\n"
      ";   Selling vectors), so it CAN read near 0 deg for two cells that\n"
      ";   are the same shape but different size -- this is most visible\n"
      ";   for high-symmetry cells (e.g. two PRIMITIVE cubic cells of\n"
      ";   different edge length, with the SAME centering, both reduce to\n"
      ";   parallel Selling vectors, so S6 angle is 0 between them; this\n"
      ";   does not hold when the two cells have different centering).\n"
      ";   A small S6 angle next to a large P3 distance is not a\n"
      ";   contradiction; trust P3 distance for overall match quality and\n"
      ";   S6 angle only for shape/axis-permutation sanity checks.\n"
      ";\n"
      ";   A match's quality tier (EXCELLENT/GOOD/POOR/DISTORTED) is always\n"
      ";   based on the PRIMITIVE-frame P3 distance, regardless of\n"
      ";   DISPLAYMODE -- it describes how good the underlying lattice\n"
      ";   match is, independent of which cell pair ends up on screen.\n"
      ";\n"
      ";   When DISPLAYMODE NEW falls back to the primitive pair (NOTE\n"
      ";   line shown), this means the reference-frame transform of THIS\n"
      ";   PARTICULAR transformation matrix did not reproduce the\n"
      ";   reference cell well, even though the primitive-space match\n"
      ";   itself may be excellent. This is expected and not a bug: when a\n"
      ";   centered lattice has multiple equally-good primitive matches,\n"
      ";   only some of their transformation matrices correctly invert the\n"
      ";   reference's specific centering relationship. Other matches for\n"
      ";   the SAME mobile cell, with a different transformation matrix,\n"
      ";   may show a good reference-frame match instead -- check\n"
      ";   neighboring matches before assuming the relationship is wrong.\n"
      ";\n"
      ";   To see exactly why a given match did or did not get a\n"
      ";   reference-frame (CONVENTIONAL) display, use DETAILS: it prints\n"
      ";   the primitive-frame and reference-frame P3/S6 numbers for every\n"
      ";   match, which is the data DISPLAYMODE's choice is based on.\n"
      ";\n"
      "; EXAMPLE SESSION\n"
      ";   MODE SUPER\n"
      ";   P 5.0 5.0 7.0 90 90 120\n"
      ";   P 5.0 5.0 14.0 90 90 120\n"
      ";   end\n"
      ";\n";
}

#endif // HELPLMP3_H
