#include <iostream>
#include <vector>
#include <string>
#include <cmath>

#include "SuperControls.h"
#include "ProgramSetup.h"
#include "Matrix_3x3.h"
#include "LRL_Cell.h"

// =============================================================================
// Supercell transformation matrices from:
//   Santoro & Mighell, Acta Cryst. A28, 284-287 (1972).
//
// Superlattices of order n are generated by integer 3x3 matrices M with
// det(M) = n.  The unique representatives are those in Hermite Normal Form
// (upper-triangular, positive diagonal, reduced off-diagonal entries):
//
//   | a  b  c |
//   | 0  d  e |     a*d*f = n,  0 <= b < d,  0 <= c,e < f
//   | 0  0  f |
//
// This enumeration implements the Santoro-Mighell procedure and yields all
// distinct superlattices of each order.
//
// Transformation:
//   LRL_Cell::Cart() returns the Cartesian basis matrix B whose columns are
//   the lattice vectors expressed in an orthonormal frame.  Under the integer
//   transformation M the new basis is
//
//       B' = M * B
//
//   The metric tensor of the supercell is then
//
//       G' = B'^T * B'  =  B^T * M^T * M * B
//
//   and LRL_Cell can be reconstructed from G' = B'^T B' by reading off the
//   six dot products of the new basis vectors.
// =============================================================================

namespace {

   // Build all 3x3 integer matrices in Hermite Normal Form with det = n.
   std::vector<Matrix_3x3> HermiteNormalForms(const int n) {
      std::vector<Matrix_3x3> matrices;

      for (int a = 1; a <= n; ++a) {
         if (n % a != 0) continue;
         const int nd = n / a;
         for (int d = 1; d <= nd; ++d) {
            if (nd % d != 0) continue;
            const int f = nd / d;

            // 0 <= b < d,  0 <= c < f,  0 <= e < f
            for (int b = 0; b < d; ++b) {
               for (int c = 0; c < f; ++c) {
                  for (int e = 0; e < f; ++e) {
                     // Upper-triangular HNF stored row-major
                     matrices.emplace_back(
                        static_cast<double>(a), static_cast<double>(b), static_cast<double>(c),
                        0.0, static_cast<double>(d), static_cast<double>(e),
                        0.0, 0.0, static_cast<double>(f)
                     );
                  }
               }
            }
         }
      }
      return matrices;
   }

   // Apply supercell transformation M to cell using the Cartesian basis.
   //
   // LRL_Cell::Cart() returns B whose columns are the lattice vectors in an
   // orthonormal frame, laid out row-major as confirmed by LRL_Vector3.cpp:
   //
   //   m[0] m[1] m[2]
   //   m[3] m[4] m[5]
   //   m[6] m[7] m[8]
   //
   // The supercell basis is  B' = M * B,  giving  G' = B'^T * B'.
   // G' is symmetric; its elements recover the six cell parameters:
   //
   //   a'        = sqrt(G'[0])       ( G'_00 )
   //   b'        = sqrt(G'[4])       ( G'_11 )
   //   c'        = sqrt(G'[8])       ( G'_22 )
   //   cos alpha = G'[5] / (b'*c')   ( G'_12 )
   //   cos beta  = G'[2] / (a'*c')   ( G'_02 )
   //   cos gamma = G'[1] / (a'*b')   ( G'_01 )

   static double SafeAcosRad(const double cosVal) {
      // Guard against floating-point drift outside [-1,1] before acos
      const double clamped = std::max(-1.0, std::min(1.0, cosVal));
      return std::acos(clamped);
   }

   LRL_Cell TransformCell(const LRL_Cell& cell, const Matrix_3x3& M) {
      const Matrix_3x3 B = cell.Cart();            // Cartesian basis of input cell
      const Matrix_3x3 Bp = M * B;                  // Cartesian basis of supercell
      const Matrix_3x3 Gp = Bp.Transpose() * Bp;    // metric tensor: G' = B'^T B'

      const double ap = std::sqrt(Gp[0]);
      const double bp = std::sqrt(Gp[4]);
      const double cp = std::sqrt(Gp[8]);

      const double alpha = SafeAcosRad(Gp[5] / (bp * cp));  // G'_12
      const double beta = SafeAcosRad(Gp[2] / (ap * cp));  // G'_02
      const double gamma = SafeAcosRad(Gp[1] / (ap * bp));  // G'_01

      return LRL_Cell(ap, bp, cp, alpha, beta, gamma);  // angles in radians
   }

} // anonymous namespace

// =============================================================================

// =============================================================================

int main() {
   std::cout << "; CmdSuper" << std::endl;

   try {
      SuperControls controls;
      const BasicProgramInput<SuperControls> dc_setup("CmdSuper", controls);

      if (dc_setup.getInputList().empty()) {
         throw std::runtime_error("; No input vectors provided");
      }

      if (controls.shouldShowControls()) {
         std::cout << controls << std::endl;
      }

      // -----------------------------------------------------------------------
      // Build the Santoro-Mighell HNF supercell matrices for the requested orders.
      // Defaults to {2, 3, 4}; overridden by ORDER or MATRIXORDER control.
      // -----------------------------------------------------------------------
      std::vector<std::pair<int, std::vector<Matrix_3x3>>> orderMatrices;
      for (const int n : controls.getOrders()) {
         orderMatrices.emplace_back(n, HermiteNormalForms(n));
      }

      // -----------------------------------------------------------------------
      // For each input cell, apply every transformation and report results.
      // -----------------------------------------------------------------------
      for (const auto& input : dc_setup.getInputList()) {
         const LRL_Cell cell = input.getCell();

         if (!controls.shouldShowOriginal()) {
            std::cout << "; Input cell: ";
         }
         std::cout << input.getLatticeType() << " " << LRL_Cell_Degrees(cell) << "\n";

         for (const auto& [order, matrices] : orderMatrices) {
            std::cout << "; --- Supercells of order " << order
               << " (" << matrices.size() << " matrices) ---\n";

            int idx = 1;
            for (const auto& M : matrices) {
               const LRL_Cell supercell = TransformCell(cell, M);
               std::cout << input.getLatticeType()
                  << " " << LRL_Cell_Degrees(supercell)
                  << " order=" << order
                  << " matrix=" << idx++
                  << "\n";
            }
         }
      }

      return 0;
   }
   catch (const std::exception& e) {
      std::cout << "; An error occurred: " << e.what() << std::endl;
      return 1;
   }
}