//// ApplyVCPSequence -- replacement for OneBound, ProcessTwoZeros, ProcessThreeZeros
////
//// BACKGROUND
//// ----------
//// In Delone/Selling reduction, a lattice point in S6 lies on a boundary of the
//// fundamental domain when one or more of its six scalars is zero. At such a
//// boundary, the Virtual Cartesian Point (VCP) operation reflects the point
//// through that boundary wall into an adjacent domain. Each of the 6 possible
//// zero positions has a corresponding VCP matrix in vcpVector.
////
//// For a point with n zeros (n = 1, 2, or 3 in practice), there are n boundary
//// walls to reflect through, and the reflections can be composed in sequence.
//// The full set of boundary-related points needed for SELLA is generated by
//// applying all possible sequences of VCP reflections, up to depth n.
////
//// COMPLETENESS ARGUMENT
//// ---------------------
//// A point with n zeros has exactly n boundary walls active. Applying one VCP
//// reflection preserves the number of zeros (the VCP matrix maps the boundary
//// structure to the adjacent domain). However the zero positions in S6 can
//// MOVE after a VCP -- a zero at slot i may appear at a different slot j in
//// the reflected point, because the VCP matrix mixes components.
////
//// For each zero position found in the CURRENT point, we apply the VCP at
//// that position and recurse. The parent point is passed to prevent immediately
//// reversing the last VCP (since each VCP is an involution: applying it twice
//// returns to the original point).
////
//// Completeness follows from three facts established empirically:
////
////   1. The 24 S6 reflections of a VCP result always include BOTH possible
////      exchange outcomes of the Delone reduction step (the two ways to
////      choose which pair of non-opposite scalars to swap). Therefore a
////      single VCP matrix per zero position, combined with StoreAllReflections,
////      generates the full boundary neighborhood for that wall.
////
////   2. The number of zeros is conserved by the VCP, so the recursion depth
////      is bounded by the original number of zeros (1, 2, or 3).
////
////   3. The parent-tracking termination condition prevents oscillation
////      (re-applying the same VCP immediately) without needing to track
////      stale wall indices that may have moved after a VCP step.
////
//// REPLACEMENT FOR OLD CODE
//// ------------------------
//// This single recursive function replaces:
////   OneBound          (1 zero case)
////   ProcessTwoZeros   (2 zero case) -- which had a bug: after applying VCP(i),
////                     the second zero may have moved from slot j to a new slot,
////                     but the old code used the original slot j for the second
////                     VCP application, giving a wrong or missing result.
////   ProcessThreeZeros (3 zero case) -- same structural bug, compounded.
////   ProcessZeros      (dispatcher) -- no longer needed
////
//// The new code finds the current zero positions at each recursive level,
//// so it always operates on the actual zero locations, not stale ones.
////
//// NEAR-ZERO VALUES
//// ----------------
//// FindS6Zeros uses exact == 0.0 comparison. This is correct here because:
////   - The entry point s6 comes from MakeSampleType which applies an integer
////     projector matrix to a Selling-reduced lattice, producing exact zeros
////     for the canonical Delone type.
////   - The VCP matrices have integer entries, so exact zeros are preserved
////     exactly through all VCP applications in the recursion.
//// Any near-zero (but not exact zero) values that arise from floating point
//// in the random lattice generation are handled in the final cleanup stages
//// (duplicate removal and projector application), not here.
//
//void SellaBuild::ApplyVCPSequence(
//   const std::string& label,
//   const EnhancedS6& s6,
//   const EnhancedS6& parent)
//{
//   // Store the current point and all its S6 reflections.
//   // The 24 reflections cover all symmetry-equivalent forms of this
//   // boundary point, including both Delone exchange variants (see fact 1).
//   StoreAllReflections(label, s6);
//
//   // Find all active boundary walls (exact zero positions) in the current point.
//   const std::vector<size_t> currentZeros = FindS6Zeros(s6);
//
//   for (const size_t z : currentZeros) {
//      // Apply the VCP reflection through wall z.
//      const EnhancedS6 next = vcpVector.applyVCP(z, s6);
//
//      // Skip if this takes us back to where we just came from.
//      // Each VCP is an involution, so vcpVector.applyVCP(z, next) == s6,
//      // and we would otherwise oscillate forever between the two points.
//      // Comparing against the immediate parent is sufficient because:
//      //   - The recursion depth is bounded by the number of zeros (<=3)
//      //   - All longer cycles are excluded by the depth bound, not by
//      //     cycle detection (cycles longer than 2 do not occur within
//      //     the bounded depth of the zero-count)
//      if (next == parent) continue;
//
//      ApplyVCPSequence(label, next, s6);
//   }
//}
//
//// Entry point -- replaces ProcessZeros, OneBound, ProcessTwoZeros,
//// ProcessThreeZeros. Pass a default-constructed (invalid) EnhancedS6
//// as the initial parent since there is no previous point.
//void SellaBuild::ProcessZeros(const std::string& label, const EnhancedS6& s6)
//{
//   ApplyVCPSequence(label, s6, EnhancedS6());
//}